language: python

python:
  - 2.6
  - 2.7
  - 3.3

env:
  global:
    - WTFORMS="<2.1"
  matrix:
    - SQLALCHEMY=0.7.10
    - SQLALCHEMY=0.8.6
    - SQLALCHEMY=0.8.6 WTFORMS="==1.0.5"
    - SQLALCHEMY=0.9.6
    - SQLALCHEMY=0.9.6 WTFORMS="==1.0.5"


# command to install dependencies
install:
  - "pip install WTForms$WTFORMS SQLAlchemy==$SQLALCHEMY"
  - "pip install ."
  - "pip install -r tests/requirements.txt"

# command to run tests
script: coverage run setup.py test
after_success:
  - pip install coveralls
  - coveralls
